image: node:24

variables:
  NODE_ENV: test
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: monster_hunter_guild
  MYSQL_ROOT_PASSWORD: root
  DATABASE_URL: mysql://root:$MYSQL_ROOT_PASSWORD@mysql:3306/monster_hunter_guild

services:
  - mysql:latest

stages:
  - install
  - build
  - check

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install --no-audit --no-fund
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

prisma:
  stage: build
  needs: [install_dependencies]
  script:
    - npm run prisma:migrate
    - npm run prisma:generate
  artifacts:
    paths:
    - src/generated

build:
  stage: build
  needs: [prisma]
  script:
    - npm run build

lint:
  stage: check
  needs: [build]
  script:
    - npm run lint

format_check:
  stage: check
  needs: [build]
  script:
    - npm run format:check

test:
  stage: check
  needs: [build,prisma]
  script:
    - npm run test:ci --silent
