image: node:24

variables:
  NODE_ENV: test
  MYSQL_DATABASE: monster_hunter_guild
  MYSQL_ROOT_PASSWORD: root
  MYSQL_ROOT_HOST: "%"
  DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  DATABASE_NAME: monster_hunter_guild
  DATABASE_HOST: mysql
  DATABASE_PORT: "3306"

services:
  - mysql:8.4

stages:
  - install
  - build
  - check

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install --no-audit --no-fund
  artifacts:
    paths:
      - node_modules/
    expire_in: 1h

prisma:
  stage: build
  needs: [install_dependencies]
  script:
    - npm run prisma:migrate
    - npm run prisma:generate
  artifacts:
    paths:
    - src/generated

build:
  stage: build
  needs: [prisma]
  script:
    - npm run build

lint:
  stage: check
  needs: [build]
  script:
    - npm run lint

format_check:
  stage: check
  needs: [build]
  script:
    - npm run format:check

test:
  stage: check
  needs: [build,prisma]
  script:
    - apt-get update && apt-get install -y default-mysql-client
    - until mysqladmin ping -h mysql -u root -proot --silent; do echo "Waiting for MySQL..."; sleep 2; done
    - npm run test:ci --silent
